### ISSUE TITLE
Multiple tables in main db using old squirrel ID = 19537 for new squirrel ID = 19851

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#101]
In the following tables: 
flastall2 (record 11391) 
flastall (record 16461) 
squirrel (record 19537) 
trapping (multiple records) 
squirrel_alias
juvenile (record 228)
census (multiple records)

old squirrel ID (= 19537) is listed for new squirrel ID = 19851 (historic_squirrel_id id = 2)

Both squirrel ids are used in table: behaviour. New squirrel ID shows up in pedigree & pedigree clean

Solution: update all tables in main to use new squirrel ID

**Comment by agmcadam** [comment]
This was an issue in the historic_squirrel_id table and not elsewhere.  This was corrected in the 2022 data cleanup.
