### ISSUE TITLE
Incorrect August census dates in 2017

### ISSUE THREAD

**Issue by emilystudd** [KluaneRedSquirrelProject/KRSP-Database-Errors#18]
Found the following errors in census dates from last august when checking this years' May census. All of these were entered with a census date of "2018-08-15" instead of "2017-08-15".  All are on KL.

M3621/M3622
H3301/H3302
H3828/H2553
H3810/H3811
M4690/M4691

**Comment by agmcadam** [comment]
These are correct in the database.  I don't know if they were fixed or I can't recreate the issue.
