### ISSUE TITLE
duplicate trapping records

### ISSUE THREAD

**Issue by swestrick** [KluaneRedSquirrelProject/KRSP-Database-Errors#20]
Several trapping records from 2018 have duplicate trapping entries, i.e. all variables are the same except trapping ID. I've only checked the entries that are relevant to the hormone processing at the moment so there could be more duplicate entries in the full database.  [https://docs.google.com/spreadsheets/d/16Ixh7WBy7nbe6X1B0asHauuhwhGAJkxGe9YSjxmEr5c/edit?usp=sharing](url)

**Comment by agmcadam** [comment]
fixed in 2018 data cleanup
