### ISSUE TITLE
Trapping records - wrong weights and/or missing records

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#32]
**wrong weight:**
23027, trap date: 2017-07-15, correct wt: 120 g (record ID 148740)
22778, trap date: 2017-07-21, correct wt = 120 (record id 149205)
22778, trap date: 7/21/17, correct wt: 120 g (record id 149205)

**missing trapping records:**
Note that we had a lot of problems with the iPods in the field in 2017, so quite a few of the trapping records are likely missing across the board for some of the squirrels. I have multiple records of these squirrels being handled on the day in question (we did an OFT that day, which has a screen capture of the date on a piece of paper in frame, as well as the date and weight records in our field notebooks and trapping calendars) 

22778, trap date: 6/30/17, correct wt: 130 g (record ids 148195, 148198, 148206 are all in the LTD with NAs for weight)

22759, trap date: 6/30/17, correct wt: 60 g 

22685, trap date 6/20/17, wt = 110 g

22985, trap date: 7/21/17, wt = 110 g <- record id 148984 (NAs for weights)

22897, trap date: 6/30/17, wt = 85 g <- record id 148193 (NAs for weights)

22759, trap date: 6/30/17, wt = 60 g

22987, trap date: 7/14/17, correct wt=108 <- this is the right date (have OFT with date in frame) - record id 148822 has date 7/17/17 (which has NAs, so this might be the record someone tried to enter for this squirrel, given they were not trapped that day)

**wrong date:**
22898, current trap date: 6/29/17, correct trap date: 7/6/17, correct wt = 76 (record id 148104)

**records that should be deleted. cant find in field books either:**
22684, date: 7/16/17, wt = 161 (record id 148781)
22986, date: 7/27/17, wt = 96 (record id 149218)
23494 date: 2017-06-23, wt=131 (record id 147785)
23573 2017-07-25, wt=121 (record id 156488)

**wrong trapping dates (verified with field books, OFT video stamps, and field notes):**

22652 (record id 147785)
wrong date: 2017-06-19
right date: 2017-06-20 <- correct date

```
#this is what my output looks like
trap= tbl(con, "trapping") %>% collect()
trap%>%filter(squirrel_id== 22652)%>%select(id, squirrel_id, date, scale_weight, wgt)
# A tibble: 5 x 5
      id squirrel_id date       scale_weight   wgt
   <dbl>       <dbl> <chr>             <int> <int>
1 147785       22652 2017-06-19          260   140
2 152229       22652 2018-04-08          355   235
3 153003       22652 2018-04-23          350   230
4 153871       22652 2018-05-12          370   220
5 155041       22652 2018-06-07          350   220
```

22719 (record id 147782)
wrong date: 2017-06-19
right date: 2017-06-20 <- correct date

22774 (record id 147809)
wrong date: 2017-06-21
right date: 2017-06-22 <- correct date

22872 (record id 148901)
wrong date: 2017-07-18
right date: 2017-07-19 <- correct date

22953 (record id 148439)
wrong date: 2017-07-07
right date: 2017-07-09 <- correct date

23040 (record id 148438)
wrong date: 2017-07-07
right date: 2017-07-09 <- correct date

**Comment by martinig** [comment]
missing trapping record:
22987, date: 7/14/17, wt=108

wrong weight (correct weights below):
22685, date 6/20/17, wt = 110
22985, date: 7/21/17, wt = 110
22897, date: 6/30/17, wt = 85
22759, date: 6/30/17, wt = 60
22778, date: 6/30/17, wt = 130 & 7/21/17, wt = 120
23031, date: 8/2/17, wt = 136

wrong date: 
22898, current date: 6/29/17, correct date: 7/6/17, wt = 76

records that should be deleted? cant find in field books either:
22684, date: 7/16/17, wt = 161 (it seems ~impossible a squirrel lost 31 g in 2 days)
22986, date: 7/27/17, wt = 96 (it seems ~impossible a squirrel gained 40g in 4 days)

**Comment by martinig** [comment]
wrong trapping dates (verified with field books, OFT video stamps, and field notes):

22652
wrong date: 2017-06-19
right date: 2017-06-20

22719
wrong date: 2017-06-19
right date: 2017-06-20

22774
wrong date: 2017-06-21
right date: 2017-06-22

22872
wrong date: 2017-07-18
right date: 2017-07-19

22953
wrong date: 2017-07-07
right date: 2017-07-09

23040
wrong date: 2017-07-07
right date: 2017-07-09

23494
wrong date: 2017-06-23
right date: 2017-06-25

23520
wrong date: 2017-07-17
right date: 2017-07-15

23566
wrong date: 2017-07-04
right date: 2017-07-14

23573
wrong date: 2017-07-25
right date: 2017-07-26

**Comment by agmcadam** [comment]
> missing trapping record:
> 22987, date: 7/14/17, wt=108
> 
> wrong weight (correct weights below):
> 22685, date 6/20/17, wt = 110
> 22985, date: 7/21/17, wt = 110
> 22897, date: 6/30/17, wt = 85
> 22759, date: 6/30/17, wt = 60
> 22778, date: 6/30/17, wt = 130 & 7/21/17, wt = 120
> 23031, date: 8/2/17, wt = 136
> 
> wrong date:
> 22898, current date: 6/29/17, correct date: 7/6/17, wt = 76
> 
> records that should be deleted? cant find in field books either:
> 22684, date: 7/16/17, wt = 161 (it seems ~impossible a squirrel lost 31 g in 2 days)
> 22986, date: 7/27/17, wt = 96 (it seems ~impossible a squirrel gained 40g in 4 days)

**Comment by agmcadam** [comment]
April.  Can you clarify that for the May 28 entry above that those first numbers are squirrel_id numbers?

**Comment by martinig** [comment]
I don’t see a May 28th entry, but all numbers that are 5 digits are squirrel_id numbers.

April

---
April Martinig, M.Sc.
Ph.D. Candidate in Ecology
University of Alberta
martinig.weebly.com<http://martinig.weebly.com>
“I do not accept the conventional order of things as a given."

On Nov 7, 2019, at 9:39 AM, Andrew McAdam <notifications@github.com<mailto:notifications@github.com>> wrote:


April. Can you clarify that for the May 28 entry above that those first numbers are squirrel_id numbers?

**Comment by agmcadam** [comment]
April for 22778, this squirrel was not handled on 6/30/2017.  Also 22579 was not caught on 6/30/2017.  22579 was caught on 7/23/2017, but the weight was correctly recorded already as 175g.  Can you please double-check these errors to make sure they are reported correctly?

**Comment by agmcadam** [comment]
As above, I am finding many problems with these errors that you have indicated.  In some cases you say that a weight is wrong, but I can find no trapping record for that day.  In other cases you say the date is wrong, but I am seeing the date already indicated as why you say is the correct date.  Please double-check these errors and make reference to particular record ids in your descriptions for clarity.

**Comment by martinig** [comment]
Hi Andrew, I updated the first comment above.

**Comment by agmcadam** [comment]
all except the request to delete records were corrected in the 2022 data cleanup.
