### ISSUE TITLE
duplicate squirrel IDs

### ISSUE THREAD

**Issue by swestrick** [KluaneRedSquirrelProject/KRSP-Database-Errors#33]
These 4 records are 2 duplicate squirrel IDs that should be merged. 

SQID: 13295 and 19729 - both records for H3570/1 on JO --- I believe 19729 is correct. 13295 has trapping records for H1622/H1623.
SQID: 22175 and 22356 - both records for H1746/M1525 on BT --- based on litter records, I believe 22175 is correct.

[duplicateSQIDs.xlsx](https://github.com/KluaneRedSquirrelProject/KRSP-Database-Errors/files/3330979/duplicateSQIDs.xlsx)

**Comment by agmcadam** [comment]
Corrected in 2019 database cleanup
