### ISSUE TITLE
Missing birth date

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#41]
Because this juvenile is missing their birth date, this is causing me problems for creating a competitor density for her (and anyone around her with a missing birth date):

squirrel_id / litter_id / mom_id
23689 / 8945 / 21075

**Comment by agmcadam** [comment]
April.  Please split these as two separate issues.  For the second issue, all of those litter_id values are in the litter table.

**Comment by agmcadam** [comment]
All of these litter_id values are in the litter table.

**Comment by martinig** [comment]
I must be doing something incorrectly.

I call the litter LTD like so:

litters<- tbl(con,"litter") %>%
select (litter_id=id, mom_id=squirrel_id, grid, yr, fieldBDate) %>%
collect()

And then I search for the corresponding litter, like so:

litters %>% filter (litter_id== 3074)

And then no records appear.


April

---
April Martinig, M.Sc.
Ph.D. Candidate in Ecology
University of Alberta
martinig.weebly.com<http://martinig.weebly.com>
“I do not accept the conventional order of things as a given."

On Jan 8, 2020, at 1:43 PM, Andrew McAdam <notifications@github.com<mailto:notifications@github.com>> wrote:


All of these litter_id values are in the litter table.

**Comment by martinig** [comment]
For now, let me keep digging into this. I've been trying to sort this out for four days now, but I must be doing something wrong - especially if they show up on your end.

**Comment by martinig** [comment]
I've resolved the issue for all but one squirrel. (modified error above)

**Comment by agmcadam** [comment]
April for this one remaining issue above, I am not sure what needs to be corrected.  Is there a field birth date that was not entered?

**Comment by martinig** [comment]
Yes, there is no field birth date entered.
