### ISSUE TITLE
No census record

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#42]
#mom's that are missing from 2004/2005 census
df <- data.frame(
squirrel_id = c("6408", "6359", "6392", "6538", "6956", "7609", "7643"),
grid = c("KL", "KL", "KL", "KL", "KL", "KL", "SU"),
date = c("2004-05-15", "2005-05-15", "2005-05-15", "2005-05-15", "2005-05-15", "2005-05-15", "2005-05-15"),
reflo = c("O10.", "-911", "-511", "-612", "B13", "H11", "D.14."),
locX=c("15", "-9", "-6", "-5", "2", "8", "4.5"),
locY=c("10.5", "11", "12", "11", "13", "11", "14.5"),
year=c("2004", "2005", "2005", "2005", "2005", "2005", "2005"),
month=c("5", "5", "5", "5", "5", "5", "5"))

**Comment by agmcadam** [comment]
For 6408, she was caught only 4 times in 2004 and only once prior to June.  So it is not surprising that she was not included in the May census.  I don't think this is an error in the database.  April, you should check the others and see if they are similar.

**Comment by martinig** [comment]
So, these moms were moms Mark seemed to have picked “off” grid/on the grid edge. Maybe that is why they are all not in the census. Maybe it is worth adding them though in case anyone wants to use Mark’s data for the juveniles he collared from those litters (similar to what I am doing)?

**Comment by agmcadam** [comment]
I'm not sure why you feel like they need to be in the census.  If they weren't censused then they should not be added.  This doesn't mean they weren't alive, just that they were not determined to live on the grid at that time.

**Comment by martinig** [comment]
I'm okay with them not being added. The reason I have to create this dataframe on my end is because I have multiple juveniles born to these mothers in my tracking data. So, when/if someone wants to create social neighbourhoods for these mothers, they need to add them to their respective grids (despite being edge squirrels).
