### ISSUE TITLE
Incorrect record in dbamidden

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#55]
I suspect incorrect August census record was input in dbamidden on SU [dbamidden id = 10134]. 1996 has spring and fall census records for squirrel_id = 3500 B9353/B9354 O/R (male), and then an additional fall census record for an O/R squirrel at a nearby reflo with different eartags (A9353/A9354) and different squirrel_id (5239), indicated as male; but flastall indicates squirrel_id = 5239 A9353/A9354 wasn't born until 1998 and is female. The 1996 records are for SU C3 & C.4

Trapping records for an O/R squirrel on SU in 1996 are for squirrel_id = 3500 B9353/B9354.

The rest of census records for squirrel_id=5239 indicate more distant reflos so I don't know that it's just matter of a wrong year being entered.

**Comment by agmcadam** [comment]
I think this was a tag problem.  This was indicated as a secondary midden, but there was no primary midden for this squirrel unless it was a tag error.  I have changed the tags and squirrel_id to B9353/B9354 (3500).
