### ISSUE TITLE
Low weights in Trapping

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#56]
Trapping ID = 21735    adult squirrel weight = 3 g  
Trapping ID = 38736   adult squirrel weight = 5 g
Trapping ID = 36312   new squirrel not tagged before, weight = 6 g
Trapping ID = 51991    adult squirrel = 51 g 
Trapping ID = 31742    adult squirrel = 53 g
Trapping ID = 151008  adult squirrel = 75 g 
Trapping ID = 129121  adult squirrel = 80 g 
Trapping ID = 151010  adult squirrel = 80 g
Trapping ID = 136535 adult squirrel = 90 g 
Trapping ID = 129124 adult squirrel = 100g
Trapping ID = 36478 three year old squirrel = 103 g 
Trapping ID = 134146 two year old squirrel = 105 g

**Comment by agmcadam** [comment]
Andrea, are you able to sleuth what correct weights ought to be or are you suggesting we delete these data?  Can you provide more context for how you know these are correct?  Have you looked at the ages of these squirrels and weights from similar dates for these animals?

**Comment by aewishart** [comment]
Apologies for the slow followup. My impression from these are that there were typos during data input, as all of these squirrels are adults (1 year of age or older) at the time of these records so should be over 100g. The databooks should have the correct answer but barring access to those, for some I can get a best guess based on trapping records close in time to the problematic records

Trapping ID = 21735 adult squirrel weight = 3 g on 1993-08-13. Squirrel was 296 g on 1993-08-02 and 298 g on 1993-08-02; reproductive condition NULL for all of these records. So weight was likely ~297g. 

Trapping ID = 38736 adult squirrel weight = 5 g on 1999-05-15, rep con 2. Squirrel was 254 g on 1999-03-27, rep con 1;  and  260 g on 1990-06-02, rep con 2. reproductive condition NULL for all of these records. Trapping records may be too far apart temporally to fill in a weight?

Trapping ID = 36312 new adult squirrel not tagged before (fate 2), weight = 6 g on 1999-05-15, rep con 2. Squirrel not trapped again until following March when it weighed 240g. 

I can continue to sleuth for the rest if databook checks are not an option, but otherwise the weights in these records should probably be deleted as they are highly unlikely for adult squirrels

**Comment by agmcadam** [comment]
weights set to NULL in 2020 data cleanup
