### ISSUE TITLE
beh LTD errors for 2018

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#57]
Behaviour LTD errors:

**Issue 1:**
Wrong squirrel id listed. Currently listed squirrel (wrong squirrel): 22990.
Correct squirrel: 22896.

Id records in question:
```
368836 
368837
368838
368839  
368840 
368841
368842 
368843
```
----

**Issue 2:** 
Wrong grid listed. 
Record id: 371948 - Correct grid: KL.
Record id: 368638 - Correct grid: KL.
Record id: 368633 - Correct grid: KL.

----

**Issue 3:**
Comma instead of period in locy record. Record id: 378517 - correct locy: 8.2 (not 8,2).

----

**Issue 4:**
Impossible sighting. Record id: 381721. Impossible because body of squirrel was recovered on August 9th (see record 381292, verified with photos and in fieldbook).

**Comment by agmcadam** [comment]
Fixed in 2020 database cleanup.
