### ISSUE TITLE
Trapping record 150778 error for squirrel ID = 22745

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#59]
Trapping table has two entries for squirrel ID = 22745: 

1. M2030/M3031 Male on KL trapped 2016-11-28; axy off at -7.6 (no colours)
2. -/M3031 Female on JO trapped 2017-07-12; euth for tissues. Only the JO squirrel appears in the juvenile table (litter 7912) and was born in 2017, which is a year after the KL male with same squirrel ID was trapped.

A male at KL -7.5 with tags M2080/M2081 (squirrel id = 22465) was given a new axy a few weeks later at the same reflo; I think this is the most likely candidate given that 3s and 8s can easily be misread for one another on the eartags, and 22465 was given an axy ~2 weeks prior ot the 2016-11-28 axy off date which fits with EKS protocols. 

**Solution: Trapping ID 150778 should have squirrel changed to M2080/M2081 (squirrel id = 22465) **

**Comment by agmcadam** [comment]
fixed in 2020 database cleanup
