### ISSUE TITLE
Weight error for Squirrel ID = 6063 at trapping ID = 41156 and tr. ID = 41289

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#60]
Squirrel ID = 6063 (adult male) has weight recorded at trapping ID = 41156 as 63 g. Two weeks prior it was recorded as 259g and four days later it was recorded as 367g (trapping ID = 41289; which may also be a weight error). About two weeks after trapping ID = 41156, the squirrel was recorded as 262g, and all subsequent weights that year and the following year are around that value. 

Solution: either check data book for trapping ID = 41156 and trapping ID 41289, or delete weights for these trapping records

**Comment by agmcadam** [comment]
fixed in 2020 database cleanup
