### ISSUE TITLE
Weight error for Squirrel ID = 10185 trapping ID = 92928

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#61]
Squirrel ID = 10185 (adult male) has weight recorded at trapping ID =92928 as 158 g. Seven days prior it was recorded as 272g and two days later it was recorded as 268g. 272 and 268 are more consistent with this individual's weights that year. Bag weights not available for any of these entries

Solution: either check data book for trapping ID = 92928, delete weight for this trapping record, or replace with 268g which was the weight recorded within a few days of this record.

**Comment by agmcadam** [comment]
fixed in 2020 database cleanup
