### ISSUE TITLE
Trapping ID = 140471 Missing bag weight subtraction for weight calculation 

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#62]
Trapping ID = 140471 for squirrel ID = 12348 (adult male) has weight as 400g which equals the scale weight. Same observer has bag weight entered as 150g for other entries made on the same date; which would give this squirrel a weight of 250g. 

Solution: subtract 150g bag weight (and add in bag weight to entry) from squirrel weight to yield 250g squirrel weight.

**Comment by agmcadam** [comment]
fixed in 2020 database cleanup
