### ISSUE TITLE
Trapping ID = 146926 Missing bag weight from weight calculations

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#63]
Trapping ID = 146926 for squirrel ID = 20904 (adult male) has weight as 290g which equals the scale weight. Same observer has bag weight entered as 125g the day prior; which would give this squirrel a more likely weight of 265g. Other squirrels trapped on this date are also missing bag weight but squirrel weights seem reasonable for those individuals. 

**Solution:** subtract 125g bag weight from squirrel weight to yield 265g squirrel weight.

**Comment by agmcadam** [comment]
fixed in 2020 database cleanup
