### ISSUE TITLE
Duplicate death records in trapping/behaviour LTD

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#65]
**Trapping LTD**

Squirrel ID: 6528 

Date: 2006-02-16 
Fate: 10 (death)

Date: 2006-03-07
Fate: 10 (death)

----------------

Squirrel ID: 6677

Date: 2005-07-16
Fate: 10 (death)

Date: 2006-05-07
Fate: 10 (death)

**Comment by martinig** [comment]
**Behaviour LTD:**

Squirrel ID: 6677

Date: 2005-07-16
Behaviour: 9 
Detail: 5

Date: 2005-07-16
Behaviour: 9 
Detail: 3

Date: 2006-04-19 
Behaviour: 9 
Detail: 3

Date: 2006-07-09 
Behaviour: 9 
Detail: 4

**Comment by agmcadam** [comment]
Redundant records deleted
