### ISSUE TITLE
Reciprocal old and new squirrel_id in historic_squirrel_ids

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#68]
table id 40: old squirrel id = 11895 new squirrel id = 19911

table id 66: old squirrel id = 19911 new squirrel id = 11895

This results in an old squirrel ID being brought in when updating supplementary files with historic_squirrel_ids. 

Proposed solution: delete data row corresponding with id = 40 in table: historic_squirrel_ids

**Comment by agmcadam** [comment]
fixed in 2021 cleanup
