### ISSUE TITLE
Missing sex for squirrel in flastall & flastall2

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#69]
Squirrel ID = 7043 is missing sex in both flastall and flastall2 tables. 

This squirrel is identified as female in squirrel table and trapping table (death record is missing sex though, so I think this is the source of the flastall error). 

Solution: add sex = female to trapping ID = 66233 and update flastall & flastall2 tables accordingly

**Comment by agmcadam** [comment]
This is more complicated than it might seem.  The death record is not for this animal.  I suspect that the death record (trapping id = 66233) is for squirrel_id  = 5893 (O/O on SU in 2004) but I cannot be sure.  The death records in trapping for squirrel_id = 7043 in trapping and behaviour are definitely wrong and were deleted.

**Comment by agmcadam** [comment]
These records weren't deleted but i deleted the squirrel id and tags from them since the identity of the squirrel was not correct
