### ISSUE TITLE
Birth year errors in pedigree 

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#70]
squirrel ID = 2628 
FLastall2 dates = 1995 but pedigree birth year = 1997 
Tables I checked that confirm 1995 birth year: dbjuvenile, litter, flastall 

**Solution:** correct pedigree birth year to 1995 instead of 1997

squirrel ID  = 265
Flastall2 dates = 1988 but pedigree birth year = 2001
Tables I checked that confirm 1988 birth year: dbjuvenile, litter, flastall 

**Solution:** correct pedigree birth year to 1988 instead of 2001

squirrel ID  = 777
Flastall2 dates = 1990 but pedigree birth year = 1993
Tables I checked that confirm 1990 birth year: dbjuvenile, litter, flastall 

**Solution:** correct pedigree birth year to 1990 instead of 1993

**Comment by martinig** [comment]
Instead of creating a new issue, the issue I found is also related to birth dates.

7459 is born 2006-04-11, but there is a behaviour record (63432) for it on 2006-03-22 (before it is even born).

**Comment by agmcadam** [comment]
Pedigree birth year errors corrected in 2022 data cleanup.  behaviour record issue above moved to a new issue.
