### ISSUE TITLE
Wrong grid for squirrel_id = 21023 behaviours

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#72]
A series of behaviours for squirrel_id = 21023 in 2016 (mode = 3) have this squirrel on AG, while the rest of the records for this squirrel are on KL for similar locations

Solution: change grid from AG to KL in the behaviour table for squirrel_id 21023

**Comment by agmcadam** [comment]
corrected in 2021 cleanup
