### ISSUE TITLE
Tagging weight incorrect for juvenile id = 15352

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#73]
The tagging weight in the juvenile table (id = 15352, squirrel_id = 24961) is likely an error (574.0 g - that's one hefty juv). 

**Solution:** Pull correct weight from nest sheets. There are no trapping records for this squirrel so I can't find likely candidate weights in the database.

**Comment by agmcadam** [comment]
I will make this NULL for now.

**Comment by agmcadam** [comment]
This was corrected to 57.4
