### ISSUE TITLE
Minor - comment errors for behaviour table 

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#77]
Comments had "bark" accidentally replaced with detail code ("5ing" should be "barking")

Behaviour table ids = 
375104
375112
375116
375383
375495
375535
375557
375579

- Seems to be a symptom of recoding focal to coded variables. Only seemed to affect these select KCH focal entries in 2017. Data are correct, but comments otherwise won't make sense to future users.

**Comment by agmcadam** [comment]
corrected during 2021 cleanup
