### ISSUE TITLE
Incorrect 'newsex' for squirrel id = 4837

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#80]
in Flastall2, squirrel _id has newsex assigned as male, but all trapping records indicate this squirrel is a female and this squirrel has three associated litter records. 

Solution: remove M from newsex variable in flastall2

**Comment by agmcadam** [comment]
Not sure where this is coming from.  I can't find this squirrel being called a male anywhere.  flastall is just a view and not a table of data.

**Comment by agmcadam** [comment]
since flastall is a view it pulls data from elsewhere.  There isn't anything to fix here.
