### ISSUE TITLE
Incorrect 'newsex' for squirrel id = 2512

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#81]
In flastall2, squirrel _id = 2512 has newsex assigned as male, but all trapping records indicate this squirrel is a female and this squirrel has two associated litter records.

Solution: remove M from newsex variable in flastall2 (keep old sex, F)

**Comment by agmcadam** [comment]
flastall is just a view.  If all other records are correct then newest error can be ignored.
