### ISSUE TITLE
Duplicate midden records for SU Q11 in dbaMidden

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#83]
Squirrel ID = 12477 has two census records at SU Q11 in the dbaMidden table in the August census

dbaMidden id = 41961 and dbaMidden id = 43279 differ only in dates; squirrel ID, defense, fate, etc. all are identical otherwise 

The dates differ only by a few days: 2011-08-09  for 41961 and 2011-08-15 for 43279. 

Solution: remove record 41961 as the census date is wrong, and the squirrel is properly censused on the correct census date in record 43279

**Comment by agmcadam** [comment]
This is correct.  Midden changeovers are supposed to be entered as a new record on the date on which they occurred.  Then the dat from the 15th is simply a regular census.
