### ISSUE TITLE
Unlikely weights in trapping table

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#84]
In the trapping table: 

**trapping id = 133728 for squirrel id = 21355:**
Both scale weight and weight =395, no bag weight. This observer (STT) had entered a bag weight of 150 for all other trapping records that day. 
**Solution:** enter 150 for bag weight and correct the squirrel weight to 245. 

**trapping id = 149472  for squirrel id = 13129:**
Both scale weight and weight =390, no bag weight. This observer (JGR) had no other trapping records that day (2017-08-02), but had a bag weight of 125 in the months before and after this record. 
Looking at surrounding records for the observer I noticed several around this date that had missing bag weights, and therefore also have uncorrected squirrel weights: 
trapping ids = 149470, 149469, 149468, and 149466
**Solution:** enter 150 for bag weight for the following trapping records: 149472, 149470, 149469, 149468, and 149466 and correct squirrel weight accordingly

**trapping id = 156614 for squirrel id = 22274:**
Scale weight = 260, bag weight = 135. Bag weight is consistent for this observer across trappings, but squirrel weight is ~100 g less than trappings 1.5 months prior. Squirrel is adult. and this trapping occurred in Aug 2018 outside breeding (and this weight loss exceeds normal post-partum weight loss). Likely that scale weight was incorrectly input as 260 when it should have been 360. 
**Solution:** enter 350 for scale weight, and correct the squirrel weight to 225. 

**trapping id = 131915 for squirrel id = 21325:**
Scale weight = squirrel weight, bag weight = NULL. This observer (AKM) had a bag weight of 140 in temporally close trapping records. 
**Solution:** enter 140 for bag weight, and correct the squirrel weight.

**trapping id = 131921, squirrel id = 19601:**
Scale weight = squirrel weight, bag weight = NULL. Observer field = NULL, so can't check bag weights (although comments indicate this trapping had an axy collar deployed, and it looks like AKM was doing axy work on this grid at this time)
**Solution:** either check databooks for AKM for this trapping, or delete the squirrel weight.

**trapping id = 131921, squirrel id = 10178:**
Comments indicate squirrel was weighed with Mettler scale = 350g, but the same squirrel trapped a week prior weighed 253 g (consistent with the range of other weights measured for this squirrel in this month). Likely an input error for the first digit. 
**Solution:** change squirrel weight to 250g. 

**General comment re: weight queries:**
I can't recall since it's been a minute since I've been in the field, but do we have a query for checking if scale weight = squirrel weight? I know there's a bag weight presence/absence query but it doesn't seem to be catching everything. A scale weight = squirrel weight query could help flag these in the field, especially if data are being entered on a computer as opposed to the KRSP app. Apologies if this is already in place!

**Comment by agmcadam** [comment]
in most cases these weights were set to null since we cannot solve many of the issues.
