### ISSUE TITLE
Behaviour mode code 

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#85]
Took me a while to get around to doing this, but this juvenile was excluded from the focal stuff because they are coded as being focals, but they aren't focals. I am the one that watched this juvenile and I watched it for a while because it was nest building, but I didn't do any focals.

Squirrel id 22758

So, the mode for these record ids should be changed from 5 to 8.

 recordid
1    370398
2    370402
3    370406
4    370393
5    370397
6    370407
7    370394
8    370395
9    370399
10   370400
11   370404
12   370396
13   370401
14   370409
15   370392
16   370408
17   370807
18   370794
19   370804
20   370810
21   370796
22   370800
23   370801
24   370802
25   370805
26   370798
27   370799
28   370809

**Comment by agmcadam** [comment]
corrected in the 2021 cleanup
