### ISSUE TITLE
Tag weight as trapping weight for squirrel ID = 1541

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#92]
Table: juvenile (juvenile table ID = 1600) for squirrel ID = 1541

Both weight and tagWT = 62.0 (pup not present at first entry)

**Solution:** weight should be empty (NA) as this is not really a "first nest entry" and the value offers nothing for growth rate calculations.

**Comment by agmcadam** [comment]
corrected in the 2021 cleanup.
This used to be the protocol when nest 1 was missed.
