### ISSUE TITLE
Mating chases list females only

### ISSUE THREAD

**Issue by martinig** [KluaneRedSquirrelProject/KRSP-Database-Errors#94]
In the behaviour LTD, these records:

39330, 39356, 39451, 39452, 39455, 39457, 39552

all only include females as those mating. Not sure what is happening, but worth investigating. :)

This problem seems to be most prevalent for records between 30000 and 70000.

**Comment by martinig** [comment]
I actually have a larger question - I am seeing the problem above again and again as I move through the comments. Someone writes "Mate chase W/Y" but then the individual is also female colours (e.g., O/W). Am I missing something here? Is this how males were entered in the database previously? 

This example is seen best here:

52355
52388

Perhaps this needs to be edited slightly? Alternatively, maybe this is a non-issue - I'm not sure if adult females engage in mating play similar to males do.

**Comment by martinig** [comment]
Records 120937 and 120938 also had a weird colour combo on the right ear (O!P). Might be worth investigating at the same time as these records above.

**Comment by martinig** [comment]
dbabehaviour records with a similar style of data input

39330, 39356, 39451, 39452, 39455, 39457, 39552, 40366, 49704, 49748, 49749, 49802, 49807, etc.

Pretty much most records with comments that talk about mating chases between 39000 and 55000.

combo: 49873 and 49869 (comments say 1 is a male...)

**Comment by agmcadam** [comment]
historically wires were also used for males.  Pipe cleaners only started to be used more recently.  The type of color cannot be used to infer sex from historical data.

**Comment by martinig** [comment]
Right, this makes sense! But, it made the comments really confusing (it looked like females were chasing females). :)

**Comment by agmcadam** [comment]
@martinig does this solve these issues?  Can this issue be closed or are there other issues in here that still need to be addressed?

**Comment by martinig** [comment]
@agmcadam The issue is solved, although a larger question to consider might be if there is a way to have the comments be more accessible? Lots of info is in the comments that doesn't transfer to the actual data row (particularly for the mating chases/Lia's stuff).
