### ISSUE TITLE
Squirrel id = 21354 weight unlikely 

### ISSUE THREAD

**Issue by aewishart** [KluaneRedSquirrelProject/KRSP-Database-Errors#99]
Squirrel id = 21354  has squirrel weight as 90 grams in trapping ID = 137352. 

Squirrel is adult at this trapping and weight 210 in last trapping prior, and 215 in next trapping. 

Bag weight consistent for observer; likely scale weight entered wrong.

**Comment by agmcadam** [comment]
corrected during 2022 data cleanup
